.github/workflows/ci.yml, .github/workflows/release.yml
- Autoformat YAML.
- Rename and re-title workflows for clarity.
- Add new dispatch event names for clarity.
=> Touch up GH Actions workflows.

README.md, docker/base/Dockerfile, docker/base/Dockerfile.ubi, docker/dotnet/Dockerfile, docker/go/Dockerfile, docker/go/Dockerfile.ubi, docker/nodejs/Dockerfile, docker/nodejs/Dockerfile.ubi, docker/pulumi/Dockerfile, docker/python/Dockerfile, docker/python/Dockerfile.ubi
=> Update images based on Snyk recommendations.

.github/workflows/release.yml, .github/workflows/sync-ecr.yml
=> Fix ECR workflow to grab Pulumi version from event by default.

.github/workflows/release.yml, .github/workflows/sync-ghcr.yml
=> Add syncing of images to GitHub Container Registry.

.github/workflows/release.yml, .github/workflows/sync-ecr.yml, .github/workflows/sync-ghcr.yml
=> Make version requried when running release workflow.

docker/go/Dockerfile, docker/go/Dockerfile.ubi, docker/pulumi/Dockerfile
=> upgraded go to latest patch 1.17.3->1.17.7

docker/pulumi/Dockerfile
Fixes #100 
I wasn't able to test one locally but let us see what CI says about it 😄
=> Install dotnet SDK v6 in Kitchen sink

CONTIBUTING.md
This contributor guide is based on Pu/pu with some modifications for this repo.
=> Add contributor guide

docker/pulumi/Dockerfile
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/123
=> Install gke-gcloud-auth-plugin

CHANGELOG.md, README.md
To be merged after the next `pulumi/pulumi` release.
=> Add CHANGELOG.md and versions to README.md

docker/java/Dockerfile.ubi
=> Install tzdata on java ubi image

.github/workflows/release.yml
Pass through env variables for tests in the release workflow.
This adds the changes from https://github.com/pulumi/pulumi-docker-containers/pull/208 and https://github.com/pulumi/pulumi-docker-containers/pull/213 to the release workflow.
=> Update test setup for release workflow

.github/scripts/matrix/gen-matrix.py, .github/scripts/matrix/gen-sync-matrix.py, .github/scripts/matrix/versions.py, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/sync-ecr.yml, .github/workflows/sync-ghcr.yml
Follow up to https://github.com/pulumi/pulumi-docker-containers/pull/226
We need to sync the new suffixed python images to GHCR & ECR
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/230
=> Sync python matrix images to GHCR and ECR

.github/workflows/ci.yml, CHANGELOG.md, README.md, docker/base/Dockerfile, docker/dotnet/Dockerfile, docker/java/Dockerfile, docker/nodejs/Dockerfile, docker/pulumi/Dockerfile, docker/python/Dockerfile
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/147
=> Update debian images to bookworm

.github/workflows/snyk-scan.yml
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/235
=> Scan the suffixed images using Snyk

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/snyk-scan.yml, .github/workflows/sync-ecr.yml, .github/workflows/sync-ghcr.yml, CHANGELOG.md, docker/pulumi/Dockerfile, tests/containers_test.go
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/237
=> Add a nonroot variant for the kitchen sink image

README.md
Add a note about the update the the language versions announced in https://www.pulumi.com/blog/docker-containers/
=> Add default version update to readme

README.md
Document how to select a non-default language version.
=> Document language version choice

.github/workflows/sync-ecr.yml, .github/workflows/sync-ghcr.yml
Follow up to https://github.com/pulumi/pulumi-docker-containers/pull/313, where I missed the sync workflow.
=> Skip missing UBI images when syncing to ECR & GHCR

.github/workflows/ci.yml
https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
=> Cancel in progress actions for PRs on subsequent pushes

.github/workflows/ci.yml
Show size and layer information about the docker image after the build
=> Print image info after build

.github/workflows/snyk-scan.yml
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/349
=> Login to docker in the scan workflow

.github/workflows/ci.yml
We don't want this action to get skipped!
=> Ensure ci-ok is always run

docker/pulumi/Dockerfile
No changes, except that this updates some dependencies that are flagged
as security issues.
=> Upgrade pulumictl

CHANGELOG.md, docker/pulumi/Dockerfile
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.6.31
=> Update aws-iam-authenticator to 0.6.31

.github/workflows/sync-ecr.yml, .github/workflows/sync-ghcr.yml, CHANGELOG.md
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/493
=> Fix ECR & GHCR sync

.github/scripts/filter-sarif.py, .github/workflows/snyk-scan.yml
See https://github.blog/changelog/2025-07-21-code-scanning-will-stop-combining-multiple-sarif-runs-uploaded-in-the-same-sarif-file/
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/405
=> Fix snyk scanning
