scripts/test-containers.sh

Remove comment before shebang in test_containers.sh to see if it fixes an error for `set -o pipefail`.

Ensure shebang is the first line of test_containers.sh

---

.github/workflows/ci.yml

We do not want the build to fail in the event that the dispatch event
does not contain the issue number to for the comment-notification job.
In the event that the the field is missing, we will simply skip the
notification.

Do not fail build on missing issue number.

---

.github/workflows/ci.yml
docker/dotnet/Dockerfile
scripts/test-containers.sh
tests/containers_test.go

Prior to this change, an integration test suite only operated on the
"kitchen sink" pulumi/pulumi image which contains all 4 supported SDKs
for Pulumi.  This change adds the ability to run the tests for a subset
of SDKs, along with actually running the appropriate test suite for the
SDK-specific Docker images during the CI build.

Add tests for UBI SDK containers.

---

.github/workflows/release.yml

It appears the workflow_dispatch trigger must be present in the main
branch to allow arbitrary execution of the Release workflow, so we need
to add this change before we can re-work the workflow on a branch.

Add release workflow triggers.

---

docker/go/Dockerfile

The PULUMI_VERSION arg was defined before the FROM directive in the
build container.  We believe this caused "latest" to be the value read
by the line that installs Pulumi, and thus led to a mismatch between a
tagged image and the version of Pulumi installed on the image.
(get.pulumi.com does not update the latest version until after the docs
are published, but the Docker images' release build fires before the
docs are updated.)
Fixes #71

Fix golang image.

---

docker/base/Dockerfile
docker/base/Dockerfile.ubi
docker/dotnet/Dockerfile
docker/dotnet/Dockerfile.ubi
docker/go/Dockerfile
docker/go/Dockerfile.ubi
docker/nodejs/Dockerfile
docker/nodejs/Dockerfile.ubi
docker/pulumi/Dockerfile
docker/python/Dockerfile
docker/python/Dockerfile.ubi

Makes PULUMI_VERSION a required argument for all Docker images.  Removes
a default value of "latest" and simplifies the `curl` command to install
Pulumi.

Make PULUMI_VERSION a required argument.

---

.github/workflows/ci.yml
README.md

We need to add back the functionality that uses the latest version
of Pulumi if no version is explicitly specified by either a
repository_dispatch or workflow_dispatch event.

Fix CI Build.

---

docker/pulumi/Dockerfile

This is very useful for our project, and it would be a nice thing to have in the next version of the Pulumi Docker Image.
Thanks

Upgrade Node.js to version 16 (LTS)

---

docker/java/Dockerfile.ubi

This installs Maven >=3.8 and Gradle >=7.4 at present time, which meets our minimum version requirements, and ensures we stay up to date with distributions as they become available.
The upside is that we do not have to manually track Maven or Gradle for updates, including security updates.
There are two obvious downsides:
1. We lose some supply chain integrity here. Is this a blocker? We already were relying on HTTPS downloads for Maven and Gradle, this introduces sdkman as an additional dependency. This is a "trusting trust" issue, I think - we need to rely on a third party or ourselves to track Maven & Gradle releases.
2. We cannot specify a semver or upper bound for Maven or Gradle, so we will automatically opt into new major versions. These are slow moving tools, but nevertheless we …

Use sdkman to install maven and gradle in UBI images

---

docker/pulumi/Dockerfile

This PR resolves https://github.com/pulumi/pulumi-docker-containers/issues/106 by pinning the version of the AZ CLI to v2.33.1.
We don't guarantee backward compatibility of tools in the kitchen sink image. If users need a later version of a tool, they should be able to update it themselves. Sound fair?

Config AZ to workaround deprecation bug

---

docker/nodejs/dnf/nodejs.module

This PR bumps the version of NodeJS to 14, which is the minimum required version used by Pulumi 3.39.1.
This fixes the broken build.
Closes https://github.com/pulumi/pulumi-docker-containers/issues/117

Bump Node12 to Node14

---

docker/base/Dockerfile
docker/go/Dockerfile
docker/java/Dockerfile
docker/nodejs/Dockerfile
docker/python/Dockerfile

An ask from our friends in the service team to ensure `curl` is present in images used in examples and documentation.
The dotnet Debian image already contained `curl`.
Resolves #119.

feat: Add curl to base and language images

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/snyk-scan.yml
.github/workflows/sync-ecr.yml
.github/workflows/sync-ghcr.yml
docker/pulumi/Dockerfile

Adds a new `build-environment` target to the all-in-one Pulumi Dockerfile, which adds `pulumictl`, `golangci-lint`, and `goreleaser` to encapsulate the tools needed to build a Terraform-boilerplate-based Pulumi provider, as laid out in
https://github.com/pulumi/pulumi-tf-provider-boilerplate.
Fixes
https://github.com/pulumi/pulumi-docker-containers/issues/111 (see that issue for further background and rationale).
Signed-off-by: Christopher Maier <chris@graplsecurity.com>

Add a providers build environment image

---

docker/go/Dockerfile
docker/go/Dockerfile.ubi

Adds gcc to the Go docker images to handle potential pulumi or pulumi test cgo dependencies that are breaking builds.
Part of #127
I'm still seeing issues with Go builds being broken.
https://github.com/pulumi/pulumi-docker-containers/actions/runs/4319115397
Might as well add gcc to make these containers less fragile in the future.
Thoughts?

handle potential cgo dependencies

---

docker/pulumi/Dockerfile

Debian "bookworm" was released on June 10, and there are some issues installing the Azure CLI and Java on bookworm. This commit changes us to go back to using Debian "bullseye" for now.
Fixes #143

Use python:3.9-slim-bullseye

---

CHANGELOG.md
README.md
docker/nodejs/Dockerfile
docker/nodejs/dnf/nodejs.module
docker/pulumi/Dockerfile

This PR upgrades Node.js in the `pulumi/pulumi` image and `pulumi/nodejs` UBI image to the Active LTS version 18, and documents our version policy to keep language runtimes up-to-date with LTS versions.
Fixes #148

Bump NodeJS in base image to 18

---

docker/pulumi/Dockerfile

Instead of /root/.dotnet
Addresses the issue #113: .NET installed under /root/.dotnet is inaccessible when run as non-root

set dotnet install dir to /usr/share/dotnet

---

docker/pulumi/Dockerfile

Started getting errors due to `no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme`

Update aws-iam-authenticator to latest

---

.github/workflows/sync-ghcr.yml

Refs https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/
GHCR is compatible with the default `GITHUB_TOKEN` and doesn't need to use pulumi-bot's PAT.
I've given the pulumi-docker-containers repo write access on the pulumi-nodejs, pulumi-go, pulumi-base, pulumi-dotnet, pulumi-python, and pulumi images.
Fixes #167

Fix GHCR sync token

---

docker/pulumi/Dockerfile

The legacy Google-hosted package repositories have gone away. See https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
When building the image, we now get the following error:
```
The repository 'http://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file
```
This change migrates to the community-owned repository.
Fixes #184

Migrate to the k8s community-owned repository

---

CHANGELOG.md
docker/nodejs/Dockerfile
docker/nodejs/Dockerfile.ubi

We're currently running into an issue installing dependencies with `npm` from the Debian Arm64 image, which is blocking releasing v3.112.0 of the images. Installing the latest version of `npm` addresses the problem.
Once this is merged, I'm going to re-kick off the release workflow for these images for v3.112.0.
Fixes #187

Install the latest version of npm

---

CHANGELOG.md
docker/pulumi/Dockerfile

This is a straightforward contribution that I need for my own stuff.
Using Oracle Cloud Kubernetes engine with pulumi requires one of the following:
1. A static access token using a service account (not ideal)
2. One IAM user for the ci/cd process with permissions to authenticate in the cluster.
The second option connects with Kubernetes using short-lived tokens emitted by the oci-cli executable. The executable will use a config file and a pem file in the ~/.oci folder (but can be configured in other ways if needed); then we can configure ~/.kube/config to use the CLI to emit the tokens.
I need this CLI installed to use in the Pulumi cloud deployments feature with native OCI authentication, as explained in the second option.
It's better to have this upstream, but I can also maintain a …

add oracle cloud cli to image

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
tests/containers_test.go

Test that the `az` CLI is working and can login.
Test that the `azure-${sdk}` templates work.
This requires the following secrets in GHA:
* ARM_CLIENT_ID
* ARM_CLIENT_SECRET
* ARM_TENANT_ID
* ARM_SUBSCRIPTION_ID
Ref https://github.com/pulumi/pulumi-docker-containers/issues/209

Test Azure CLI and templates

---

CHANGELOG.md
docker/java/Dockerfile.ubi
tests/containers_test.go

We need to install `java-11-openjdk-devel`, not `java-11-openjdk-headless` to have a full Java dev environment.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/210

Fix compilation issue when running azure-java in the UBI pulumi-java image

---

.github/workflows/ci.yml
CHANGELOG.md
tests/containers_test.go

Test that the aws CLI is working and can login.
Test that the aws-${sdk} templates work.
This requires the following secrets in GHA:
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* AWS_CI_ROLE_ARN
Stacked on https://github.com/pulumi/pulumi-docker-containers/pull/212
Ref https://github.com/pulumi/pulumi-docker-containers/issues/209

Test AWS CLI and templates

---

CHANGELOG.md
docker/pulumi/Dockerfile

We had previously pinned `az` to version 2.33.1 to work around an issue with a deprecation warning. The underlying issue in the Azure SDK has since been fixed in https://github.com/pulumi/pulumi-azure-native/issues/1566
Note: we have tests that check that the `az` works (= can login and get account info)

Unpin Azure CLI version

---

.github/workflows/ci.yml
.github/workflows/release.yml

Update the go action and setup caching and run the CI workflow when tests or CI workflow definitions change.

Cache go dependencies in CI

---

.github/scripts/gen-matrix.py
.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
docker/dotnet/Dockerfile
docker/go/Dockerfile
docker/nodejs/Dockerfile
docker/python/Dockerfile

Create per language version images for python 3.9 to 3.12. The image without suffix `pulumi/pulumi-python` continues to use 3.9.
Other languages or UBI based images are not matrixed, but this PR puts in place most of the infrastructure for this. To generate the matrix, we use a python script that creates a list of `include` entries for the matrix. We do this instead of using the normal way to specify a matrix using variables because each language has its own range of versions.
For example for Python 3.12 we get the tags/manifests:
* pulumi-python-3.12:latest
* pulumi-python-3.12:3.127.0
* pulumi-python-3.12:3.127.0-debian
* pulumi-python-3.12:3.127.0-debian-arm64
* pulumi-python-3.12:3.127.0-debian-amd64
Example on my docker hub: …

Matrix Python debian images

---

.github/workflows/release.yml

- Add missing configure-aws-credentials action for UBI images
- Use $DOCKER_ORG in image name
- Free disk space for kitchen sink
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/241

Fix docker release job

---

CHANGELOG.md
docker/pulumi/Dockerfile
tests/containers_test.go

After the update to Debian 12, `corepack` was not installed anymore in the kitchen sink image. This is due to the installation method for the nodesource Debian repo having changed.
Update the installation method used for nodejs, and add tests to ensure `corepack` is present.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/246

Update nodejs installation script in kitchen sink

---

CHANGELOG.md
docker/go/Dockerfile
docker/go/Dockerfile.ubi
tests/containers_test.go

Add `$GOPATH/bin` to `$PATH` so that go based tools can easily be installed in the container. This matches the setup in the `pulumi/pulumi` image.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/220

Add $GOPATH/bin to $PATH for go containers

---

.github/workflows/ci.yml
tests/containers_test.go

Test that the GCP CLI can connect and retrieve basic project information.
Test that GCP templates work across languages.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/209

Test GCP CLI & projects

---

CHANGELOG.md
docker/pulumi/Dockerfile

This images is used for pulumi devcontainer and running many pulumi make commands require jq installed

Install jq in kitchen sink image

---

.github/scripts/matrix/gen-matrix.py
.github/scripts/matrix/gen-sync-matrix.py
.github/scripts/matrix/versions.py
CHANGELOG.md

Introduce new images for each Nodejs LTS version: `pulumi-nodejs-{18,20,22}`. The `pulumi-nodejs` image continues to use Nodejs 18.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/254

Matrix Nodejs debian images across LTS versions

---

.github/scripts/matrix/gen-matrix.py
.github/scripts/matrix/gen-sync-matrix.py
.github/scripts/matrix/versions.py
.github/workflows/ci.yml
CHANGELOG.md
docker/go/Dockerfile

Create suffixed images for dotnet: pulumi-dotnet-6.0 & pulumi-dotnet-8.0. The pulumi-dotnet image continues to use dotnet 6.0.

Matrix dotnet debian images

---

.github/workflows/release.yml

These env variables were added to the test workflow in https://github.com/pulumi/pulumi-docker-containers/pull/250, but I forgot to add them to the release workflow.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/261

Add GCP env vars to the release workflow

---

.github/workflows/release.yml

Follow up to https://github.com/pulumi/pulumi-docker-containers/pull/262

Authenticate with GCP and pass through env vars in release job

---

.github/workflows/release.yml

We need this to auth with GCP
Follow up to https://github.com/pulumi/pulumi-docker-containers/pull/263

Add id-token permissions to release jobs

---

tests/containers_test.go

Every image should include git. Add a test that ensures this is the case.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/271

Test that git is installed

---

README.md

This is outdated/wrong, some images use ENTRYPOINT, others use CMD.
https://github.com/pulumi/pulumi-docker-containers/issues/270 tracks unifying/rethinking this.

Remove usage section from readme

---

README.md

The default Java version was bumped to 17 when we updated the base OS to Debian 12. We had never actually published the Java images before to any registry, so we didn't hold back this update.

Update doc on default Java version

---

.github/workflows/release.yml
.github/workflows/sync-ecr.yml
.github/workflows/sync-ghcr.yml

We need to push the default images for the UBI variants ,for example
pulumi-python:3:134.0-ubi.
We also need to skip trying to sync the versions for Python 3.10 and
Nodejs 22 for UBI, since these do not exist, see https://github.com/pulumi/pulumi-docker-containers/blob/fdcbab706212b8e2aafa55470934a3cabe05447e/.github/workflows/ci.yml#L395-L398
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/279
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/278

Fix release & and sync jobs for ubi images

---

.github/workflows/release.yml

We need to create the tag `latest-nonroot` during the build so we can later (conditionally) push it.

Fix release for pulumi:latest-nonroot

---

.github/workflows/release.yml
.github/workflows/sync-ecr.yml
.github/workflows/sync-ghcr.yml
docker/pulumi/Dockerfile

I would like to setup devcontainers for use by the developers when they are working on my custom provider. Currently since there isn't an arm64 version, the experience is slow and painful on Apple Silicon. This change updates the Dockerfile so that all that is needed is the `--platform=linux/arm64` in the build and it will take care of switching out all the places needed to build. Note: The build matrices will need to be updated if this is something you would consider adding.
Thanks.

Update pulumi dockerfile to multiarch

---

.github/workflows/release.yml

The default image name was copied from the debian version without adapting it.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/291
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/290

Fix copy-pasta in ubi release

---

.github/workflows/release.yml
.github/workflows/sync-ecr.yml
.github/workflows/sync-ghcr.yml

We had to disable the release builds of these images on arm64 because it takes too long to install the Python versions provided by the image when running in Docker + QEMU.
ARM64 runners should become available for OSS projects later this year, see https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/
Once we can use these, we can re-enable the ARM64 build.
Ref https://github.com/pulumi/pulumi-docker-containers/issues/297

Disable arm64 build for kitchen sink and provider-build-environment

---

.github/scripts/matrix/versions.py
.github/workflows/ci.yml
CHANGELOG.md

New language versions are out, let’s get then into the kitchen sink and as slim language specific versions.

Add Node.js 23 and Python 3.13 to the kitchen sink and as per-language versions

---

docker/pulumi/Dockerfile

Follow up to https://github.com/pulumi/pulumi-docker-containers/pull/309
This didn't actually add the new versions to the kitchen sink, only to the language specific images.

Add Python 3.13 and Node.js 23 to kitchen sink

---

.github/workflows/release.yml

Added for CI in https://github.com/pulumi/pulumi-docker-containers/pull/309, but  I forgot to add this to the release workflow

Skip Node.js 23 and Python 3.13 for UBI release

---

.github/workflows/ci.yml
tests/containers_test.go

Our templates have been updated to use .NET 8.0, so they won't run anymore on .NET 6.0.

Skip template tests on .NET 6.0 image

---

.github/workflows/release.yml

Pass through the language version, so we can skip the donet template tests when running on dotnet 6.0. Our templates have been updated to use 8.0
Follow up to https://github.com/pulumi/pulumi-docker-containers/pull/320 which updated the PR workflow, but not the release workflow.

Skip dotnet 6.0 tests in release script

---

.github/workflows/sync-ecr.yml
.github/workflows/sync-ghcr.yml

The script got mistakently changed to `gen-matrix.py`  in https://github.com/julienp/pulumi-docker-containers/commit/4d5ec96ec3a4c80cf0c85219eb87523f0fb4e908 from
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/315
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/314

Fix sync jobs

---

.github/workflows/release.yml

https://github.com/pulumi/pulumi-docker-containers/pull/326/ updated the UBI imags so that we can build for the missing Python and Node.js versions, but forgot to updated the release script.

Release all UBI images

---

.github/scripts/matrix/versions.py
CHANGELOG.md
README.md
docker/pulumi/Dockerfile
tests/testdata/python-default/__main__.py

To run on Python 3.13 you need at least pulumi [3.136.0](https://github.com/pulumi/pulumi/releases/tag/v3.136.0), which was released October 8. Defaulting to Python 3.13 causes issues for anyone on an older version. Python 3.12 support goes back to [3.103](https://github.com/pulumi/pulumi/releases/tag/v3.103.0), released in January.

Default to Python 3.12 instead of 3.13

---

CHANGELOG.md
docker/pulumi/Dockerfile
docker/python/Dockerfile
docker/python/Dockerfile.ubi
tests/containers_test.go

Now that the Pulumi CLI supports uv out of the box, include it in the docker images.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/340

Add uv to images that include Python

---

.github/scripts/filter-sarif.py
.github/workflows/snyk-scan.yml

Fix scanning for all images by correctly setting the platform. Scan results are upload to GitHub code scanning.

Fix Snyk scanning and upload results

---

CHANGELOG.md
docker/go/Dockerfile

Missed this in https://github.com/pulumi/pulumi-docker-containers/pull/236, flagged by Snyk due to curl vulnerabilities

Update Go container to debian:12

---

CHANGELOG.md
docker/pulumi/Dockerfile

With Poetry 2.0 `virtualenvs.prefer-active-python` has been replaced by the inverse setting `virtualenvs.use-poetry-python` and the former is now the default.
https://github.com/python-poetry/poetry/pull/9786

Update for Poetry 2.0

---

.github/workflows/ci.yml

This way we can set up the merges to require this job to pass. This is useful for renovate-bot so it can automerge.

Add a ci-ok job that requires all the matrix jobs

---

.github/workflows/ci.yml

This saves us ~15 minutes on the slowest CI job 🎉

Run the nonroot tests in parallel with the root tests

---

tests/go.mod
tests/go.sum

Fixes https://github.com/pulumi/pulumi-docker-containers/issues/373 & https://github.com/pulumi/pulumi-docker-containers/issues/372
Once this is merged, we can merge https://github.com/pulumi/pulumi-docker-containers/pull/374 to prevent this from happening in the future

Fix pulumi/pkg version

---

.github/scripts/matrix/gen-matrix.py
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/snyk-scan.yml
.github/workflows/sync-ecr.yml
.github/workflows/sync-ghcr.yml
CHANGELOG.md
tests/containers_test.go

ARM runners are now available for public repos https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/297
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/211

Build kitchen sink for arm64

---

.github/workflows/snyk-scan.yml

To avoid pulling the snyk image too often due to a very large matrix, we generate a matrix without architecure, and run the scan twice in each job, once for amd64 and once for arm64.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/396#event-16175823330

Combine scan jobs for arm64 and amd64 debian SDK images

---

.github/workflows/snyk-scan.yml

Since we are now uploading two files per matrix job, we need to provide a custom `category` so that GitHub codeql can differentiate the runs.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/399

Set codeql category for debian images

---

docker/pulumi/Dockerfile

This should fix a detected vulnerability in `golang.org/x/crypto/ssh`. This is not relevant for our usage, but gets flagged by scanners.

Update goreleaser to 2.6.1

---

CHANGELOG.md
docker/pulumi/Dockerfile

Update pulumictl, golanglint-ci and goreleaser in the build-environment image

Update tools in build-environment

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/snyk-scan.yml
.github/workflows/sync-ecr.yml

These changes migrate this repo's GitHub Actions Workflows to use ESC secrets instead of GitHub Secrets.
The changes are largely mechanical:
- Common configuration for all ESC actions within a workflow is added to the workflow's environment variables
- Permissions are expanded as necessary for workflows that do not grant `id-token: write` permissions
- `read-all` permissions are replaced with the union of all explicit read permissions and `id-token: write`
- Default permissions are replaced with `write-all`, which is the equivalent of all explicit write permissions and
`id-token: write`
- Explicit permissions are modified to grant `id-token: write`
- A step that fetches ESC secrets and populates environment variables is added to each step that reads secrets
- Direct references to secrets …

Use ESC secrets

---

.github/workflows/release.yml
.github/workflows/snyk-scan.yml

Follow up to https://github.com/pulumi/pulumi-docker-containers/pull/453
It looks like `DOCKER_HUB_TOKEN` is set on this repo as an actions secret. The ESC environment has a `DOCKER_HUB_PASSWORD` instead.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/466

Fix docker login
